services:
    bot:
        build: .
        volumes:
          - sqlite_data:/app/data
        environment:
          - SQLITE_PATH=/app/data/settings.db
        restart: unless-stopped
        env_file:
          - .env

volumes:
    sqlite_data:
